(() => {
 'use strict';
 const usable=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
 function epoch(row){if(usable(row?.epoch))return Number(row.epoch);const t=Date.parse(row?.received_at||'');return Number.isFinite(t)?t/1000:null;}
 function gaps(rows,minutes=10){const sorted=[...(rows||[])].filter(r=>epoch(r)!==null).sort((a,b)=>epoch(a)-epoch(b)),out=[];let count=0;for(const row of sorted){const prev=out.at(-1);if(prev&&epoch(row)-epoch(prev)>minutes*60){out.push({_gap:true,_archiveGap:true,epoch:(epoch(prev)+epoch(row))/2,_gapTime:(epoch(prev)+epoch(row))*500});count++;}out.push(row);}return {rows:out,gaps:count};}
 function bounds(day){const midnight=key=>{const utc=Date.parse(key+'T00:00:00Z');const part=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Dublin',timeZoneName:'shortOffset'}).formatToParts(new Date(utc)).find(p=>p.type==='timeZoneName')?.value||'GMT';const m=part.match(/GMT([+-])(\d+)(?::(\d+))?/);return utc/1000-(m?(m[1]==='-'?-1:1)*(Number(m[2])*3600+Number(m[3]||0)*60):0);};const next=new Date(Date.parse(day+'T12:00:00Z')+86400000).toISOString().slice(0,10);return {start:midnight(day),end:midnight(next)};}
 function coverageText(row,day){if(!row||!usable(row.coverage_percent))return 'Coverage unavailable · daily totals may be incomplete.';const pct=Number(row.coverage_percent),scope=row.coverage_scope==='since_first_observation'?'since collection began that day':(row.day_in_progress||day===new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Dublin'}).format(new Date()))?'so far today':'of the day';const partial=pct<98||row.coverage_scope==='since_first_observation';return `${partial?'Partial archive':'Archive coverage'} · ${pct.toFixed(1)}% ${scope} · ${row.actual_slots}/${row.expected_slots} five-minute slots. ${partial?'Daily totals and extremes may be incomplete.':'Coverage describes saved observations, not sensor accuracy.'}`;}
 window.ParknacrossArchiveQuality={epoch,gaps,bounds,coverageText};
 async function dashboard(){const node=document.getElementById('dashboardCoverage');if(!node)return;try{const base=(window.PARKNACROSS_CONFIG?.apiBase||'https://parknacross-weather.dave-s-carter.workers.dev').replace(/\/$/,'');const response=await fetch(base+'/coverage?days=2',{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error();const data=await response.json(),day=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Dublin'}).format(new Date()),row=data.days?.find(x=>x.day===day);node.textContent=coverageText(row,day);node.dataset.state=!row?'unknown':row.coverage_percent<98||row.coverage_scope==='since_first_observation'?'partial':'complete';}catch(_){node.textContent='Archive coverage temporarily unavailable; readings continue independently.';node.dataset.state='unknown';}}
 window.addEventListener('DOMContentLoaded',dashboard);if(document.readyState!=='loading')dashboard();(window.ParknacrossRefresh?.every || setInterval)(dashboard,300000);
})();
