import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=name=>fs.readFileSync(new URL('../'+name,import.meta.url),'utf8');
const warningsWindow={};vm.runInNewContext(source('weather-warnings.js'),{window:warningsWindow,Date});const now=Date.now(),iso=delta=>new Date(now+delta).toISOString();const valid=warningsWindow.ParknacrossWarnings.select([{level:'Yellow',expires:iso(-1000)},{level:'Red',onset:iso(-1000),expires:iso(10000)},{level:'Orange',onset:iso(20000),expires:iso(30000)},{level:'Red',type:'potato blight'}],now);assert.equal(valid.length,2);assert.equal(valid[0].level,'red');assert.equal(valid[1].upcoming,true);
// Deadline includes a body that never finishes, and bypasses other providers.
let deadline,called=0,aborted=false;const requestWindow={fetch:async(input,init)=>{called++;init?.signal?.addEventListener('abort',()=>aborted=true);return {status:200,arrayBuffer:()=>new Promise(()=>{})};}};vm.runInNewContext(source('site-request.js'),{window:requestWindow,location:{href:'https://example.test'},URL,Response,AbortController,setTimeout:fn=>(deadline=fn,1),clearTimeout(){}});const hung=requestWindow.fetch(new URL('https://parknacross-weather.dave-s-carter.workers.dev/current'));await Promise.resolve();deadline();await assert.rejects(hung,/too long/);assert.equal(aborted,true);await requestWindow.fetch('https://example.test/other');assert.equal(called,2);
async function offlineInstall(missing){const handlers={},cache=new Map(),deleted=[];let skipped=0;const context={self:{registration:{scope:'https://example.test/'},addEventListener:(name,fn)=>handlers[name]=fn,skipWaiting:async()=>skipped++,clients:{claim:async()=>{}}},caches:{open:async()=>({put:async(req,res)=>cache.set(req.url,res),match:async key=>cache.get(key)}),keys:async()=>['parknacross-previous','other-app'],delete:async key=>deleted.push(key)},fetch:async request=>({ok:!request.url.endsWith(missing||'impossible')}),Request,URL,AbortController,setTimeout,clearTimeout};vm.runInNewContext(source('service-worker.js'),context);let promise;handlers.install({waitUntil:p=>promise=p});if(missing){await assert.rejects(promise,/Incomplete offline update/);assert.equal(skipped,0);assert.equal(deleted.length,0);}else{await promise;assert.equal(skipped,1);handlers.activate({waitUntil:p=>promise=p});await promise;assert.deepEqual(deleted,['parknacross-previous']);}}
await offlineInstall('site-request.js');await offlineInstall();
// Test the real Worker warning route without any database binding or schema calls.
const worker=(await import('../_worker/worker.mjs')).default;globalThis.caches={default:{match:async()=>null,put:async()=>{}}};
const originalFetch=globalThis.fetch;let calls=[];const ctx={waitUntil(){}};const request=()=>new Request('https://worker.test/met/warnings');
try{
 globalThis.fetch=async url=>{calls.push(String(url));return new Response(JSON.stringify([{level:'Red',headline:'Wexford',expires:iso(100000)}]),{headers:{'Content-Type':'application/json'}});};let response=await worker.fetch(request(),{},ctx);assert.equal(response.status,200);assert.equal((await response.json()).warnings[0].level,'Red');assert.equal(calls.length,1);
 globalThis.fetch=async url=>String(url).endsWith('.json')?new Response('{}'):new Response('<h2>Weather Warnings</h2><h3>Status Yellow - Rain warning for Wexford</h3><p>Rain.</p><p>Valid: 16:00 Thursday 08/10/2099 to 04:00 Friday 09/10/2099</p><h2>Marine Warnings</h2>');response=await worker.fetch(request(),{},ctx);assert.equal(response.status,200);let data=await response.json();assert.equal(data.source,'https://www.met.ie/warnings-today.html');assert.equal(data.warnings[0].onset,'2099-10-08T15:00:00.000Z');
 globalThis.fetch=async()=>new Response('<html>Unavailable</html>',{status:503});response=await worker.fetch(request(),{},ctx);assert.equal(response.status,503);assert.match((await response.json()).error,/unavailable/);
}finally{globalThis.fetch=originalFetch;}
console.log('PASS: warning expiry/severity, body deadlines, offline cache preservation, schema-independent official warning fallback and honest failure.');
// Share five-minute history cache keys; preserve explicitly fixed historical intervals.
const historyRequests=[];const historyWindow={fetch:async input=>{historyRequests.push(new URL(typeof input==='string'?input:input.url));return new Response('{}',{headers:{'Content-Type':'application/json'}});}};
vm.runInNewContext(source('site-request.js'),{window:historyWindow,location:{href:'https://parknacrossweather.ie/'},URL,Request,Response,AbortController,setTimeout,clearTimeout});
await historyWindow.fetch('https://parknacross-weather.dave-s-carter.workers.dev/history?hours=48');
await historyWindow.fetch('https://parknacross-weather.dave-s-carter.workers.dev/history?hours=168');
await historyWindow.fetch(new Request('https://parknacross-weather.dave-s-carter.workers.dev/history?hours=24'));
await historyWindow.fetch('https://parknacross-weather.dave-s-carter.workers.dev/history?from_epoch=100&to_epoch=200');
assert.match(historyRequests[0].searchParams.get('_window'),/^\d+$/);assert.equal(historyRequests[0].searchParams.get('_window'),historyRequests[1].searchParams.get('_window'));assert.equal(historyRequests[2].searchParams.get('hours'),'24');assert.equal(historyRequests[3].searchParams.has('_window'),false);
console.log('PASS: rolling archive cache windows and fixed historical intervals.');
