(() => {
 'use strict';const key='parknacross:background-alerts:v1',base=window.PARKNACROSS_API_BASE||window.PARKNACROSS_CONFIG?.apiBase||'https://parknacross-weather.dave-s-carter.workers.dev';
 const read=()=>{try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}};
 const write=value=>{localStorage.setItem(key,JSON.stringify(value));};
 let serverKey=null,busy=false,syncPending=false,syncJob=null;
 const status=text=>{const n=document.getElementById('backgroundAlertStatus');if(n)n.textContent=text;};
 function isActive(){return read()?.active===true&&typeof Notification!=='undefined'&&Notification.permission==='granted';}
 async function subscription(){if(!navigator.serviceWorker)return null;const registration=await navigator.serviceWorker.ready;return registration.pushManager?.getSubscription();}
 async function request(action,sub,prefs){const saved=read(),headers={'Content-Type':'application/json'};if(saved?.token)headers.Authorization='Bearer '+saved.token;const response=await fetch(`${base}/push/subscription`,{method:'POST',headers,body:JSON.stringify({action,subscription:sub.toJSON(),preferences:prefs}),signal:AbortSignal.timeout(15000)}),data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'Background service unavailable');return data;}
 function ui(){const b=document.getElementById('backgroundAlertToggle');if(b){b.disabled=busy||(!serverKey&&!read()?.active);b.textContent=read()?.active?'Turn off background alerts':'Enable background alerts';b.setAttribute('aria-pressed',String(read()?.active===true));}}
 async function history(){const list=document.getElementById('recentWeatherAlerts');if(!list)return;list.replaceChildren();if(!isActive()){const p=document.createElement('p');p.textContent='No background alerts are enabled on this device.';list.append(p);return;}try{const sub=await subscription();if(!sub)throw Error('Subscription missing');const data=await request('status',sub);const rows=Array.isArray(data.history)?data.history:[];if(!rows.length){const p=document.createElement('p');p.textContent='No alerts have been sent to this subscription yet.';list.append(p);}for(const row of rows.slice(-10).reverse()){const p=document.createElement('p'),strong=document.createElement('strong');strong.textContent=String(row.title||'Weather alert');p.append(strong,document.createTextNode(' · '+new Date(row.at).toLocaleString('en-IE',{timeZone:'Europe/Dublin',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})+' Irish time. '+String(row.body||'')+' Accepted by the push service; device delivery can be delayed.'));list.append(p);}}catch{const p=document.createElement('p');p.textContent='Recent alert history could not be checked.';list.append(p);}}
 async function stop(){syncPending=false;if(syncJob)await syncJob;const sub=await subscription();let removed=false,closed=!sub;try{if(sub){await request('remove',sub);removed=true;}}catch{}if(sub)closed=await sub.unsubscribe();if(!closed&&!removed)throw Error('Could not confirm alerts stopped');write(null);status('Background alerts are off on this device.');ui();await history();}

 async function sync(){if(!isActive())return;syncPending=true;if(syncJob)return syncJob;syncJob=(async()=>{while(syncPending&&isActive()){syncPending=false;try{const sub=await subscription();if(!sub){write(null);ui();return;}await request('save',sub,window.PWAlerts?.loadSettings());status('Background alerts are on · notifications can arrive while the site is closed. Delivery depends on your device and connection.');}catch{status('Background settings could not be saved. Previously saved settings remain in use; retry shortly.');}}})().finally(()=>{syncJob=null;});return syncJob;}
 window.PWBackgroundAlerts={isActive,stop,sync};
 document.addEventListener('DOMContentLoaded',()=>{const button=document.getElementById('backgroundAlertToggle');if(!button)return;
 async function check(){button.disabled=true;if(!('PushManager' in window)||!navigator.serviceWorker||!('Notification' in window)){status('Background alerts are not supported here. On iPhone or iPad, open the installed Home Screen app.');return;}try{const response=await fetch(`${base}/push/public-key`,{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error('Unavailable');const data=await response.json();if(!data.available||!data.public_key)throw Error('Unavailable');serverKey=data.public_key;status(isActive()?'Background alerts are enabled on this device.':'Optional background alerts can arrive while the website is closed.');ui();await history();}catch{serverKey=null;status('Background delivery is temporarily unavailable. Page-open alerts remain available.');ui();}}
 button.addEventListener('click',async()=>{if(busy||(!serverKey&&!read()?.active))return;busy=true;ui();let created=null;try{if(read()?.active){await stop();return;}const permission=Notification.permission==='granted'?'granted':await Notification.requestPermission();if(permission!=='granted'){status('Background alerts were not enabled. Notification permission is required.');return;}status('Enabling background alerts…');const registration=await navigator.serviceWorker.ready,bytes=Uint8Array.from(atob(serverKey.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));created=await registration.pushManager.getSubscription();if(created&&!read()?.token){await created.unsubscribe();created=null;}created=created||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});const settings=window.PWAlerts?.loadSettings()||{},data=await request('save',created,settings);try{write({active:true,token:data.management_token});}catch{await request('remove',created);await created.unsubscribe();throw Error('This browser could not save the subscription');}window.PWAlerts?.saveSettings({...settings,enabled:true});window.PWAlerts?.refreshUI();status('Background alerts are on. Select the weather events below; quiet hours use Irish time.');await history();}catch(error){if(created&&!read()?.active)await created.unsubscribe().catch(()=>{});status('Background alerts could not be changed. '+String(error.message));}finally{busy=false;ui();}});
 document.getElementById('retryBackgroundAlerts')?.addEventListener('click',()=>{serverKey?sync():check();});document.getElementById('refreshAlertHistory')?.addEventListener('click',history);
 window.addEventListener('parknacross:alert-settings',()=>{if(window.PWAlerts?.loadSettings().enabled===false&&isActive())stop().catch(()=>status('Could not confirm background alerts stopped. Retry Turn off background alerts.'));else sync();});check();
 });
})();
