(() => {
 const cfg=window.PARKNACROSS_CONFIG||{},API=cfg.apiBase,$=id=>document.getElementById(id),set=(id,v)=>{const e=$(id);if(e)e.textContent=v};
 const API_TIMEOUT_MS=12000;
 const usable=v=>v!==null&&v!==undefined&&v!==""&&Number.isFinite(Number(v));
 const n=(v,d=1)=>usable(v)?Number(v).toFixed(d):"--";
 const comp=d=>{if(!usable(d))return"--";const a=["N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"];return a[Math.round((((Number(d)%360)+360)%360)/22.5)%16]};
 const timeOpts={timeZone:"Europe/Dublin",hour:"2-digit",minute:"2-digit"};
 const dateOpts={timeZone:"Europe/Dublin",weekday:"short",day:"numeric",month:"short"};
 let localObservationEpoch=null;
 const sourceEpoch=raw=>{if(typeof raw==="number"||(typeof raw==="string"&&/^\d{10,13}$/.test(raw))){const value=Number(raw);return value<1e12?value*1000:value;}const parsed=Date.parse(typeof raw==="string"&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?$/.test(raw)?raw+"Z":raw||"");return Number.isFinite(parsed)?parsed:null;};
 const ageLabel=ms=>{const minutes=Math.max(0,Math.floor((Date.now()-ms)/60000));return minutes<2?"just now":minutes<60?`${minutes} min ago`:minutes<1440?`${Math.floor(minutes/60)} hr ago`:`${Math.floor(minutes/1440)} days ago`;};
 const formatSourceStamp=raw=>{const ms=sourceEpoch(raw);return ms===null?"time unavailable":`${new Date(ms).toLocaleString("en-IE",{timeZone:"Europe/Dublin",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})} Irish time · ${ageLabel(ms)}`;};
 function updateLocalFreshness(){const node=$("coastLocalFreshness");if(!node)return;node.textContent=localObservationEpoch===null?"Parknacross local readings · observation time unavailable":`Parknacross local readings · observed ${formatSourceStamp(localObservationEpoch)}`;}
 const duration=ms=>{if(!Number.isFinite(ms)||ms<0)return"";const mins=Math.max(0,Math.round(ms/60000));const h=Math.floor(mins/60),m=mins%60;if(h&&m)return`${h}h ${m}m`;if(h)return`${h}h`;return`${m}m`};
 const seaDataTime=item=>{const raw=item?.observation_time||item?.timestamp||item?.model_time||null;return raw?sourceEpoch(raw):null};
 const freshSeaReference=item=>{const time=seaDataTime(item);return time!==null&&Date.now()-time>=-2*3600000&&Date.now()-time<=12*3600000};
 function localSeaEstimate(local,m2){
   const model=usable(local?.sea_surface_temperature_c)?Number(local.sea_surface_temperature_c):null;
   const buoy=usable(m2?.sea_surface_temperature_c)?Number(m2.sea_surface_temperature_c):null;
   if(model===null||model<2||model>25)return null;
   if(buoy===null||buoy<2||buoy>25||!freshSeaReference(m2))return{display:`${n(model)} °C`,summary:`around ${n(model)}°C`,confidence:"Low confidence · coastal model only",crossChecked:false};
   /* M2 is an observation but is about 110 km offshore; the coastal model is
      local but not a beach measurement. A range is more honest than an
      arbitrary weighted average presented with false 0.1°C precision. */
   const low=Math.round(Math.min(model,buoy)*10)/10,high=Math.round(Math.max(model,buoy)*10)/10;
   return{display:`${low.toFixed(1)}–${high.toFixed(1)} °C`,summary:`estimated ${low.toFixed(1)}–${high.toFixed(1)}°C`,confidence:"Low–moderate confidence · model and offshore observation range",crossChecked:true};
 }
 const swimState={wind:null,gust:null,direction:null,exposure:null,air:null,rain:null,observedAt:null,seaText:null,tide:null,warning:null};
 function renderSwimSummary(){
   const parts=[];
   if(usable(swimState.air))parts.push(`Air ${n(swimState.air)}°C`);
   if(swimState.seaText)parts.push(`water temperature ${swimState.seaText}`);
   if(usable(swimState.wind)){const direction=usable(swimState.direction)?` ${comp(swimState.direction)}`:"";const exposure=swimState.exposure?` · ${swimState.exposure.toLowerCase()}`:"";parts.push(`wind ${n(swimState.wind)} km/h${direction}${exposure}`);}
   if(usable(swimState.rain)&&Number(swimState.rain)>0)parts.push(`rain rate ${n(swimState.rain)} mm/h`);else if(usable(swimState.rain))parts.push("no rain detected at the station");
   if(swimState.tide)parts.push(swimState.tide);
   if(swimState.warning)parts.push(swimState.warning);
   set("swimSummary",parts.length?`${parts.map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join(". ")}. Check the official forecast and assess conditions at the water yourself.`:"Conditions are temporarily unavailable. Check official forecasts before travelling.");
   if(swimState.observedAt){const ms=sourceEpoch(swimState.observedAt);if(ms!==null)set("swimUpdated",`Parknacross station reading · observed ${formatSourceStamp(ms)}.`);}
 }
 async function get(p){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),API_TIMEOUT_MS);try{const r=await fetch(`${API}${p}`,{cache:"no-store",signal:controller.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(timer)}}
 async function loadCurrent(){try{const c=await get("/current");set("coastWind",usable(c.wind_speed_kmh)?`${n(c.wind_speed_kmh)} km/h`:"--");set("coastGust",usable(c.wind_gust_kmh)?`${n(c.wind_gust_kmh)} km/h`:"--");set("coastDir",usable(c.wind_direction_deg)?`${comp(c.wind_direction_deg)} · ${Math.round(Number(c.wind_direction_deg))}°`:"--");set("coastAirTemp",usable(c.temperature_c)?`${n(c.temperature_c)} °C`:"--");set("coastAirDetail",usable(c.humidity)?`Humidity ${Math.round(Number(c.humidity))}% · Parknacross`:"Parknacross observation");set("coastRain",usable(c.rain_rate_mm_h)?`${n(c.rain_rate_mm_h)} mm/h`:"--");set("coastRainDetail",usable(c.rain_daily_mm)?`${n(c.rain_daily_mm)} mm recorded today`:"Current station rain rate");Object.assign(swimState,{wind:c.wind_speed_kmh,gust:c.wind_gust_kmh,direction:c.wind_direction_deg,air:c.temperature_c,rain:c.rain_rate_mm_h,observedAt:c.received_at||c.timestamp||(usable(c.epoch)?Number(c.epoch)*1000:null)});localObservationEpoch=sourceEpoch(swimState.observedAt);updateLocalFreshness();if(usable(c.wind_direction_deg)){const d=((Number(c.wind_direction_deg)%360)+360)%360;let label,detail;if(d>=45&&d<165){label="Onshore";detail="Wind arriving from the Irish Sea";}else if(d>=225&&d<345){label="Offshore";detail="Wind arriving from inland";}else if(d>=165&&d<225){label="Alongshore · S";detail="Southerly component along the coast";}else{label="Alongshore · N";detail="Northerly component along the coast";}swimState.exposure=label;set("coastExposure",label);set("coastExposureDetail",`${detail} · ${comp(d)} ${Math.round(d)}°`);}renderSwimSummary();}catch{set("coastWind","Unavailable");set("coastGust","Unavailable");set("coastDir","Unavailable");set("coastAirTemp","Unavailable");set("coastAirDetail","Local station feed temporarily unavailable");set("coastRain","Unavailable");set("coastRainDetail","Local station feed temporarily unavailable");set("coastExposure","Unavailable");swimState.wind=swimState.gust=swimState.direction=swimState.air=swimState.rain=swimState.observedAt=null;localObservationEpoch=null;updateLocalFreshness();renderSwimSummary();}}
 async function loadSeaTemperature(){try{const s=await get("/marine/sea-temperature");const local=s.local_model||(s.source_type==="model"?s:null);const m2=s.m2_buoy||((s.source_type==="observation"&&s.station_id==="M2")?s:null);const stamp=v=>{const t=v?.model_time||v?.observation_time||v?.timestamp||null;return t?formatSourceStamp(t):null};const estimate=localSeaEstimate(local,m2);if(estimate){set("localSeaTemp",estimate.display);const t=stamp(local);set("localSeaTempTime",t?`${estimate.confidence} · model ${n(local?.sea_surface_temperature_c)}°C · ${t}`:`${estimate.confidence} · model ${n(local?.sea_surface_temperature_c)}°C`);swimState.seaText=estimate.summary;}else{set("localSeaTemp","Unavailable");set("localSeaTempTime","Coastal model temporarily unavailable");swimState.seaText=null;}if(m2&&usable(m2.sea_surface_temperature_c)){set("m2SeaTemp",`${n(m2.sea_surface_temperature_c)} °C`);const source=m2.source_short||m2.source||"M2 buoy",t=stamp(m2);set("m2SeaTempTime",t?`${source} · ${t}`:source);}else{set("m2SeaTemp","Unavailable");set("m2SeaTempTime","M2 buoy observation temporarily unavailable");}window.ParknacrossFreshness?.render("localSeaFreshness",s,local?.model_time||local?.timestamp,24,"Coastal model update");window.ParknacrossFreshness?.render("m2Freshness",s,m2?.observation_time||m2?.timestamp,12,"M2 observation");renderSwimSummary();}catch(error){console.error("Sea temperature:",error);set("localSeaTemp","Unavailable");set("localSeaTempTime","Coastal estimate temporarily unavailable");set("localSeaFreshness","Feed unavailable");set("m2Freshness","Feed unavailable");set("m2SeaTemp","Unavailable");set("m2SeaTempTime","M2 buoy observation temporarily unavailable");swimState.seaText=null;renderSwimSummary();}}
 async function loadMarine(){try{const m=await get("/met/marine");const localWarning=Boolean(m.local_warning_relevant||m.local_gale_warning||m.local_small_craft_warning);let warningTitle="No warning in force";if(localWarning){if(m.local_gale_warning&&m.local_small_craft_warning)warningTitle="Gale and Small Craft warnings";else if(m.local_gale_warning)warningTitle="Gale warning";else if(m.local_small_craft_warning)warningTitle="Small Craft warning";else warningTitle="Marine warning in force";}swimState.warning=localWarning?`${warningTitle} relevant to the local marine sector`:"no relevant marine warning reported";set("coastWarn",warningTitle);set("coastIssued",`${m.local_warning_sector||"Local marine sector"} · Met Éireann · Issued: ${m.local_warning_issued_text||m.issued||"unavailable"}${m.local_warning_valid_text?` · Valid: ${m.local_warning_valid_text}`:""}`);if(localWarning&&m.local_warning_onset){const onset=Date.parse(m.local_warning_onset),expires=Date.parse(m.local_warning_expires);if(onset>Date.now()){warningTitle+=" · upcoming";set("coastWarn",warningTitle);}else if(Number.isFinite(expires)&&expires<=Date.now()){set("coastWarn","Warning validity has ended");swimState.warning="warning validity has ended; check the latest official bulletin";}};set("marineForecastUpdated",m.issued?`Met Éireann forecast issue · ${formatSourceStamp(m.issued)}`:"Met Éireann forecast issue time unavailable");if(m.local_area){set("marineArea",m.local_area.area||"South Irish Sea");set("marineWind",m.local_area.wind||"Marine forecast details unavailable");set("marineWeather",m.local_area.weather||"Marine forecast details unavailable");set("marineVis",m.local_area.visibility||"Marine forecast details unavailable")}else{set("marineWind","Marine forecast details unavailable");set("marineWeather","Marine forecast details unavailable");set("marineVis","Marine forecast details unavailable")}set("marineOutlook",m.outlook?.text||"Further outlook unavailable");window.ParknacrossFreshness?.render("marineForecastUpdated",m,m.issued_at||m.issued,24,"Forecast issued");renderSwimSummary();}catch{set("coastWarn","Marine forecast unavailable");set("coastIssued","Met Éireann feed temporarily unavailable");set("marineForecastUpdated","Met Éireann update time unavailable");set("marineWind","Marine forecast temporarily unavailable");set("marineWeather","Marine forecast temporarily unavailable");set("marineVis","Marine forecast temporarily unavailable");set("marineOutlook","Marine forecast temporarily unavailable");swimState.warning="official marine forecast unavailable";renderSwimSummary();}}
 async function loadTides(){try{const t=await get("/marine/tides?station=Arklow"),a=(t.events||[]).filter(x=>x&&x.time&&Number.isFinite(new Date(x.time).getTime())).sort((x,y)=>new Date(x.time)-new Date(y.time));if(!a.length){set("nextTide","Unavailable");set("nextTideTime","No Arklow tide predictions returned");$("tideList").textContent="Arklow tide predictions are temporarily unavailable.";swimState.tide="Arklow tide prediction unavailable";renderSwimSummary();return;}window.ParknacrossFreshness?.render("tideFreshness",t,t.issued||t.updated_at||t.freshness?.retrieved_at,24,"Prediction feed update");const now=new Date(),previous=[...a].reverse().find(x=>new Date(x.time)<=now)||null,next=a.find(x=>new Date(x.time)>now)||null;let state="--";if(previous)state=previous.type==="low"?"Rising ↑":"Falling ↓";else if(next)state=next.type==="high"?"Rising ↑":"Falling ↓";set("nextTide",state);if(next){const label=next.type==="high"?"High":"Low",until=duration(new Date(next.time)-now),height=usable(next.height_m)?` · ${n(next.height_m,2)} m OD Malin`:"";const time=new Date(next.time).toLocaleTimeString("en-IE",timeOpts);set("nextTideTime",`${label} ${time} · in ${until}${height}`);swimState.tide=`Arklow tide ${state.replace(/[↑↓]/g,"").trim().toLowerCase()} toward ${label.toLowerCase()} water at ${time}`;}else{set("nextTideTime","Arklow prediction · next event unavailable");swimState.tide="next tide prediction unavailable";}$("tideList").innerHTML=a.filter(x=>new Date(x.time)>now-6*3600000).slice(0,8).map(x=>`<article class="tide-item"><span>${new Date(x.time).toLocaleDateString("en-IE",dateOpts)}</span><strong>${x.type==="high"?"High water":"Low water"}</strong><time>${new Date(x.time).toLocaleTimeString("en-IE",timeOpts)}</time><b>${usable(x.height_m)?`${n(x.height_m,2)} m OD Malin`:"--"}</b></article>`).join("")||"No recent or upcoming Arklow tide predictions returned.";renderSwimSummary();}catch{set("tideFreshness","Tide prediction feed unavailable.");set("nextTide","Unavailable");set("nextTideTime","Arklow prediction temporarily unavailable");$("tideList").textContent="Arklow tide predictions are temporarily unavailable.";swimState.tide="tide prediction unavailable";renderSwimSummary();}}
 document.addEventListener("DOMContentLoaded",()=>{set("year",new Date().getFullYear());loadCurrent();loadMarine();loadTides();loadSeaTemperature();(window.ParknacrossRefresh?.every || setInterval)(loadCurrent,60*1000);(window.ParknacrossRefresh?.every || setInterval)(loadMarine,15*60*1000);(window.ParknacrossRefresh?.every || setInterval)(loadTides,30*60*1000);(window.ParknacrossRefresh?.every || setInterval)(loadSeaTemperature,30*60*1000);(window.ParknacrossRefresh?.every || setInterval)(updateLocalFreshness,60*1000);});
})();

