(() => {
 const cfg=window.PARKNACROSS_CONFIG||{},API=cfg.apiBase,$=id=>document.getElementById(id),set=(id,v)=>{const e=$(id);if(e)e.textContent=v};
 const usable=v=>v!==null&&v!==undefined&&v!==""&&Number.isFinite(Number(v));
 const n=(v,d=1)=>usable(v)?Number(v).toFixed(d):"--";
 const comp=d=>{if(!usable(d))return"--";const a=["N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"];return a[Math.round((((Number(d)%360)+360)%360)/22.5)%16]};
 const timeOpts={timeZone:"Europe/Dublin",hour:"2-digit",minute:"2-digit"};
 const dateOpts={timeZone:"Europe/Dublin",weekday:"short",day:"numeric",month:"short"};
 const duration=ms=>{if(!Number.isFinite(ms)||ms<0)return"";const mins=Math.max(0,Math.round(ms/60000));const h=Math.floor(mins/60),m=mins%60;if(h&&m)return`${h}h ${m}m`;if(h)return`${h}h`;return`${m}m`};
 async function get(p){const r=await fetch(`${API}${p}`,{cache:"no-store"});if(!r.ok)throw new Error();return r.json()}
 async function loadCurrent(){try{const c=await get("/current");set("coastWind",usable(c.wind_speed_kmh)?`${n(c.wind_speed_kmh)} km/h`:"--");set("coastGust",usable(c.wind_gust_kmh)?`${n(c.wind_gust_kmh)} km/h`:"--");set("coastDir",usable(c.wind_direction_deg)?`${comp(c.wind_direction_deg)} · ${Math.round(Number(c.wind_direction_deg))}°`:"--");if(usable(c.wind_direction_deg)){const d=((Number(c.wind_direction_deg)%360)+360)%360;let label,detail;if(d>=45&&d<165){label="Onshore";detail="Wind arriving from the Irish Sea";}else if(d>=225&&d<345){label="Offshore";detail="Wind arriving from inland";}else if(d>=165&&d<225){label="Alongshore · S";detail="Southerly component along the coast";}else{label="Alongshore · N";detail="Northerly component along the coast";}set("coastExposure",label);set("coastExposureDetail",`${detail} · ${comp(d)} ${Math.round(d)}°`);}}catch{set("coastWind","--");set("coastGust","--");set("coastDir","--");set("coastExposure","--");}}
 async function loadSeaTemperature(){try{const s=await get("/marine/sea-temperature");const local=s.local_model||(s.source_type==="model"?s:null);const m2=s.m2_buoy||((s.source_type==="observation"&&s.station_id==="M2")?s:null);const stamp=v=>{const t=v?.model_time||v?.observation_time||v?.timestamp||null;return t?new Date(t).toLocaleString("en-IE",{timeZone:"Europe/Dublin",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}):null};if(local&&usable(local.sea_surface_temperature_c)){set("localSeaTemp",`${n(local.sea_surface_temperature_c)} °C`);const source=local.source_short||local.source||"Local marine model",t=stamp(local);set("localSeaTempTime",t?`${source} · ${t}`:source);}else{set("localSeaTemp","Unavailable");set("localSeaTempTime","Local model temporarily unavailable");}if(m2&&usable(m2.sea_surface_temperature_c)){set("m2SeaTemp",`${n(m2.sea_surface_temperature_c)} °C`);const source=m2.source_short||m2.source||"M2 buoy",t=stamp(m2);set("m2SeaTempTime",t?`${source} · ${t}`:source);}else{set("m2SeaTemp","Unavailable");set("m2SeaTempTime","M2 buoy observation temporarily unavailable");}}catch(error){console.error("Sea temperature:",error);set("localSeaTemp","Unavailable");set("localSeaTempTime","Local model temporarily unavailable");set("m2SeaTemp","Unavailable");set("m2SeaTempTime","M2 buoy observation temporarily unavailable");}}
 async function loadMarine(){try{const m=await get("/met/marine");const localWarning=Boolean(m.local_warning_relevant||m.local_gale_warning||m.local_small_craft_warning);let warningTitle="No warning in force";if(localWarning){if(m.local_gale_warning&&m.local_small_craft_warning)warningTitle="Gale and Small Craft warnings";else if(m.local_gale_warning)warningTitle="Gale warning";else if(m.local_small_craft_warning)warningTitle="Small Craft warning";else warningTitle="Marine warning in force";}set("coastWarn",warningTitle);set("coastIssued",m.local_warning_sector?`${m.local_warning_sector} · Met Éireann`:(m.issued?`Issued ${new Date(m.issued).toLocaleString("en-IE",{timeZone:"Europe/Dublin",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}`:"Met Éireann"));if(m.local_area){set("marineArea",m.local_area.area);set("marineWind",m.local_area.wind);set("marineWeather",m.local_area.weather);set("marineVis",m.local_area.visibility)}set("marineOutlook",m.outlook?.text||"--");}catch{set("coastWarn","Marine forecast unavailable");}}
 async function loadTides(){try{const t=await get("/marine/tides?station=Arklow"),a=(t.events||[]).filter(x=>x&&x.time).sort((x,y)=>new Date(x.time)-new Date(y.time));if(!a.length)return;const now=new Date(),previous=[...a].reverse().find(x=>new Date(x.time)<=now)||null,next=a.find(x=>new Date(x.time)>now)||null;let state="--";if(previous)state=previous.type==="low"?"Rising ↑":"Falling ↓";else if(next)state=next.type==="high"?"Rising ↑":"Falling ↓";set("nextTide",state);if(next){const label=next.type==="high"?"High":"Low",until=duration(new Date(next.time)-now),height=usable(next.height_m)?` · ${n(next.height_m,2)} m OD Malin`:"";set("nextTideTime",`${label} ${new Date(next.time).toLocaleTimeString("en-IE",timeOpts)} · in ${until}${height}`);}else set("nextTideTime","Arklow prediction · next event unavailable");$("tideList").innerHTML=a.filter(x=>new Date(x.time)>now-6*3600000).slice(0,8).map(x=>`<article class="tide-item"><span>${new Date(x.time).toLocaleDateString("en-IE",dateOpts)}</span><strong>${x.type==="high"?"High water":"Low water"}</strong><time>${new Date(x.time).toLocaleTimeString("en-IE",timeOpts)}</time><b>${usable(x.height_m)?`${n(x.height_m,2)} m OD Malin`:"--"}</b></article>`).join("");}catch{set("nextTideTime","Arklow prediction temporarily unavailable");}}
 document.addEventListener("DOMContentLoaded",()=>{set("year",new Date().getFullYear());loadCurrent();loadMarine();loadTides();loadSeaTemperature();setInterval(loadCurrent,60*1000);setInterval(loadMarine,15*60*1000);setInterval(loadTides,30*60*1000);setInterval(loadSeaTemperature,30*60*1000);});
})();
