(() => {
 'use strict';const $=id=>document.getElementById(id);let sequence=0;
 async function preview(params,button){const ticket=++sequence,status=$('downloadPreviewStatus'),host=$('downloadPreview');if(!status||!host)return;button.disabled=true;status.textContent='Checking the selected export without downloading it…';host.replaceChildren();
  try{const base=(window.PARKNACROSS_CONFIG?.apiBase||'https://parknacross-weather.dave-s-carter.workers.dev').replace(/\/$/,''),response=await fetch(base+'/export-preview?'+params,{cache:'no-store',signal:AbortSignal.timeout(20000)});if(!response.ok){const data=await response.json().catch(()=>({}));throw Error(response.status===404?'Deploy Worker v38.4.90 to enable previews. CSV downloads remain available.':data.error||`Preview failed (${response.status}).`);}const data=await response.json();if(ticket!==sequence)return;
   const fmt=epoch=>Number.isFinite(Number(epoch))&&epoch!==null?new Date(Number(epoch)*1000).toLocaleString('en-IE',{timeZone:'Europe/Dublin',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'No observations';status.textContent=`${data.count.toLocaleString('en-IE')} observations available · ${fmt(data.first_epoch)} to ${fmt(data.last_epoch)} · ${Number(data.coverage_percent||0).toFixed(1)}% of requested five-minute slots captured. Missing values remain blank; available dates do not imply uninterrupted coverage.`;
   const fields=document.createElement('p');fields.textContent='CSV columns: '+(data.columns||[]).join(', ');host.append(fields);const note=document.createElement('p');note.textContent='Sample: first three observations in the selected range. Times shown in Irish local time.';host.append(note);const wrap=document.createElement('div');wrap.className='preview-table-wrap';const table=document.createElement('table');table.className='preview-table';const head=document.createElement('tr');for(const label of ['Observation','Temperature °C','Rain rate mm/h','Soil moisture %']){const th=document.createElement('th');th.scope='col';th.textContent=label;head.append(th);}const thead=document.createElement('thead');thead.append(head);table.append(thead);const tbody=document.createElement('tbody');for(const row of data.sample||[]){const tr=document.createElement('tr');for(const value of [fmt(row.epoch),row.temperature_c,row.rain_rate_mm_h,row.soil_moisture_pct]){const td=document.createElement('td');td.textContent=value===null||value===undefined?'':String(value);tr.append(td);}tbody.append(tr);}table.append(tbody);wrap.append(table);host.append(wrap);
  }catch(error){if(ticket===sequence)status.textContent=error.message||'Preview unavailable.';}finally{button.disabled=false;}
 }
 document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.preview-export').forEach(button=>button.addEventListener('click',()=>preview('days='+encodeURIComponent(button.dataset.days),button)));$('previewCustomExport')?.addEventListener('click',event=>{const from=$('exportFrom').value,to=$('exportTo').value;if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to){$('downloadPreviewStatus').textContent='Choose a valid start and end date.';return;}preview('from='+encodeURIComponent(from)+'&to='+encodeURIComponent(to),event.currentTarget);});});
})();
