(() => {
 'use strict';const entries=()=>Array.isArray(window.PARKNACROSS_MAINTENANCE_LOG)?window.PARKNACROSS_MAINTENANCE_LOG.filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x.date)):[];
 const bounds=day=>window.ParknacrossArchiveQuality?.bounds(day)||{start:Date.parse(day+'T00:00:00Z')/1000,end:Date.parse(day+'T00:00:00Z')/1000+86400};
 function list(host,items){if(!host)return;host.replaceChildren();if(!items.length){host.textContent='No dated maintenance entries in this period.';return;}for(const item of items){const p=document.createElement('p');p.className='maintenance-event';p.textContent=`${item.date} · ${item.title} · ${item.detail||item.type||''}`;host.append(p);}}
 function dayHost(){let host=document.getElementById('dayMaintenance');if(!host){const title=document.getElementById('dayDetailTitle');if(title){host=document.createElement('div');host.id='dayMaintenance';host.className='maintenance-day-notes';title.parentElement.append(host);}}return host;}
 function renderDay(day){list(dayHost(),entries().filter(x=>x.date===day));}
 function renderCharts(charts,rows){const epochs=(rows||[]).map(x=>Number(x.epoch)).filter(Number.isFinite);if(!epochs.length)return;const first=Math.min(...epochs),last=Math.max(...epochs),items=entries().filter(x=>{const b=bounds(x.date);return b.end>=first&&b.start<=last;});for(const chart of charts){if(!chart?.options?.scales?.x||chart.config?.type!=='line')continue;chart.$maintenance=items;chart.update('none');}let host=document.getElementById('graphMaintenance');if(!host){const title=document.getElementById('graphRangeTitle');if(title){host=document.createElement('div');host.id='graphMaintenance';host.className='maintenance-chart-notes';title.parentElement.append(host);}}if(host&&items.length){host.replaceChildren();const details=document.createElement('details'),summary=document.createElement('summary'),content=document.createElement('div');summary.textContent=`${items.length} recorded maintenance update${items.length===1?'':'s'} in this period`;details.append(summary,content);host.append(details);list(content,items);}else list(host,items);if(items.length&&host){const intro=document.createElement('p');intro.textContent='Shaded bands mark recorded change dates; exact times were not recorded.';host.prepend(intro);}}
 window.Chart?.register?.({id:'parknacrossMaintenanceBands',beforeDatasetsDraw(chart){const {ctx,chartArea,scales}=chart;if(!chartArea||!scales?.x?.getPixelForValue)return;for(const item of chart.$maintenance||[]){const b=bounds(item.date),left=Math.max(chartArea.left,scales.x.getPixelForValue(b.start*1000)),right=Math.min(chartArea.right,scales.x.getPixelForValue(b.end*1000));if(right<=left)continue;ctx.save();ctx.fillStyle='rgba(239,198,121,.12)';ctx.fillRect(left,chartArea.top,right-left,chartArea.bottom-chartArea.top);ctx.restore();}}});
 window.ParknacrossMaintenance={renderCharts,renderDay};
})();
