const API_BASE="https://parknacross-weather.dave-s-carter.workers.dev";const $=id=>document.getElementById(id);const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};const usable=v=>v!==null&&v!==undefined&&v!==""&&Number.isFinite(Number(v));const n=(v,d=1)=>usable(v)?Number(v).toFixed(d):"--";
async function getJSON(path){const r=await fetch(`${API_BASE}${path}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(d?.error)throw new Error(d.error);return d}
function dateLabel(day){if(!day)return"--";const d=new Date(`${day}T12:00:00Z`);return new Intl.DateTimeFormat("en-IE",{day:"numeric",month:"short"}).format(d)}
function monthName(date){return new Intl.DateTimeFormat("en-IE",{month:"long",year:"numeric",timeZone:"Europe/Dublin"}).format(date)}
function average(values){const v=values.map(Number).filter(Number.isFinite);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null}
function maxRow(rows,field){return rows.reduce((b,r)=>!usable(r[field])?b:(!b||Number(r[field])>Number(b[field])?r:b),null)}
function minRow(rows,field){return rows.reduce((b,r)=>!usable(r[field])?b:(!b||Number(r[field])<Number(b[field])?r:b),null)}
function buildStory(rows,meanTemp,totalRain,high,low,gust,wettest){if(!rows.length)return"No monthly archive data is available yet.";const bits=[];if(usable(meanTemp))bits.push(`The mean temperature so far is ${n(meanTemp)}°C`);if(usable(high?.high_c)&&usable(low?.low_c))bits.push(`temperatures have ranged from ${n(low.low_c)}°C to ${n(high.high_c)}°C`);if(usable(totalRain))bits.push(`${n(totalRain)} mm of rain has been recorded`);if(usable(wettest?.rain_mm)&&Number(wettest.rain_mm)>0)bits.push(`the wettest day so far brought ${n(wettest.rain_mm)} mm`);if(usable(gust?.peak_gust_kmh))bits.push(`the strongest gust has reached ${n(gust.peak_gust_kmh)} km/h`);return bits.length?`${bits.join(", ")}.`:"Monthly observations are still building."}
async function load(){try{const now=new Date();const prefix=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Dublin",year:"numeric",month:"2-digit"}).format(now);const [daily,climate]=await Promise.all([getJSON("/daily?days=62"),getJSON("/climate-summary")]);const rows=(Array.isArray(daily.days)?daily.days:[]).filter(r=>String(r.day||"").startsWith(prefix));const high=maxRow(rows,"high_c"),low=minRow(rows,"low_c"),gust=maxRow(rows,"peak_gust_kmh"),wettest=maxRow(rows,"rain_mm"),solar=maxRow(rows,"solar_peak_w_m2");const totalRain=rows.reduce((s,r)=>s+(usable(r.rain_mm)?Number(r.rain_mm):0),0);const wet=rows.filter(r=>usable(r.rain_mm)&&Number(r.rain_mm)>0).length;const dry=rows.filter(r=>usable(r.rain_mm)&&Number(r.rain_mm)<=0).length;const meanTemp=usable(climate.station_month_mean_temperature_c)?Number(climate.station_month_mean_temperature_c):average(rows.filter(r=>usable(r.high_c)&&usable(r.low_c)).map(r=>(Number(r.high_c)+Number(r.low_c))/2));const avgPressure=average(rows.map(r=>r.avg_pressure_hpa));const avgHigh=average(rows.map(r=>r.high_c));set("monthTitle",`${monthName(now)} · Parknacross`);set("monthSubtitle",rows.length?`Month-to-date report based on ${rows.length} archived day${rows.length===1?"":"s"}.`:"Waiting for archived station days.");set("monthStory",buildStory(rows,meanTemp,totalRain,high,low,gust,wettest));set("meanTemp",usable(meanTemp)?`${n(meanTemp)} °C`:"--");set("monthHigh",usable(high?.high_c)?`${n(high.high_c)} °C`:"--");set("monthHighDate",high?dateLabel(high.day):"--");set("monthLow",usable(low?.low_c)?`${n(low.low_c)} °C`:"--");set("monthLowDate",low?dateLabel(low.day):"--");set("monthRain",`${n(totalRain)} mm`);set("wettestDay",usable(wettest?.rain_mm)?`${n(wettest.rain_mm)} mm`:"--");set("wettestDayDate",wettest?dateLabel(wettest.day):"--");set("wetDays",String(wet));set("dryDays",String(dry));set("daysCaptured",String(rows.length));if(rows.length)set("capturePeriod",`${dateLabel(rows[0].day)} to ${dateLabel(rows[rows.length-1].day)}`);set("monthGust",usable(gust?.peak_gust_kmh)?`${n(gust.peak_gust_kmh)} km/h`:"--");set("monthGustDate",gust?dateLabel(gust.day):"--");set("monthPressure",usable(avgPressure)?`${n(avgPressure)} hPa`:"--");set("monthSolar",usable(solar?.solar_peak_w_m2)?`${Math.round(Number(solar.solar_peak_w_m2))} W/m²`:"--");set("monthSolarDate",solar?dateLabel(solar.day):"--");set("avgHigh",usable(avgHigh)?`${n(avgHigh)} °C`:"--");if(rows.length){const firstDay=Number(String(rows[0].day).slice(8,10));set("partialNote",firstDay>1?`Partial-month archive: station data for this month currently begins on ${dateLabel(rows[0].day)}. Statistics above only use days with archived observations.`:"Month-to-date figures use all archived station days available so far.");}}
catch(e){console.error("Monthly report:",e);set("monthSubtitle","The monthly report is temporarily unavailable.");set("monthStory","Archived station data could not be loaded. Please try again shortly.");}}
document.addEventListener("DOMContentLoaded",()=>{set("year",new Date().getFullYear());load();setInterval(load,15*60*1000)});
