const API_BASE="https://parknacross-weather.dave-s-carter.workers.dev";
const $=id=>document.getElementById(id);
const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};
const usable=v=>v!==null&&v!==undefined&&v!==""&&Number.isFinite(Number(v));
const n=(v,d=1)=>usable(v)?Number(v).toFixed(d):"--";
const TZ="Europe/Dublin";
async function getJSON(path){const r=await fetch(`${API_BASE}${path}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(d?.error)throw new Error(d.error);return d}
function dateLabel(day){if(!day)return"--";const d=new Date(`${day}T12:00:00Z`);return new Intl.DateTimeFormat("en-IE",{day:"numeric",month:"short",timeZone:TZ}).format(d)}
function monthLabel(key){const d=new Date(`${key}-15T12:00:00Z`);return new Intl.DateTimeFormat("en-IE",{month:"long",year:"numeric",timeZone:"UTC"}).format(d)}
function currentMonthKey(){const parts=new Intl.DateTimeFormat("en-GB",{timeZone:TZ,year:"numeric",month:"2-digit"}).formatToParts(new Date());const map=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${map.year}-${map.month}`}
function average(values){const v=values.map(Number).filter(Number.isFinite);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null}
function maxRow(rows,field){return rows.reduce((b,r)=>!usable(r[field])?b:(!b||Number(r[field])>Number(b[field])?r:b),null)}
function minRow(rows,field){return rows.reduce((b,r)=>!usable(r[field])?b:(!b||Number(r[field])<Number(b[field])?r:b),null)}
function buildStory(rows,meanTemp,totalRain,high,low,gust,wettest){if(!rows.length)return"No archive data is available for this month.";const bits=[];if(usable(meanTemp))bits.push(`Mean archived temperature was approximately ${n(meanTemp)}°C`);if(usable(high?.high_c)&&usable(low?.low_c))bits.push(`temperatures ranged from ${n(low.low_c)}°C to ${n(high.high_c)}°C`);if(usable(totalRain))bits.push(`${n(totalRain)} mm of rain was recorded`);if(usable(wettest?.rain_mm)&&Number(wettest.rain_mm)>0)bits.push(`the wettest day brought ${n(wettest.rain_mm)} mm`);if(usable(gust?.peak_gust_kmh))bits.push(`the strongest gust reached ${n(gust.peak_gust_kmh)} km/h`);return bits.length?`${bits.join(", ")}.`:"Monthly observations are still building."}
function populatePicker(keys,selected){const picker=$("monthPicker");if(!picker)return;picker.innerHTML="";[...keys].sort().reverse().forEach(key=>{const o=document.createElement("option");o.value=key;o.textContent=monthLabel(key);o.selected=key===selected;picker.append(o)});picker.addEventListener("change",()=>{const u=new URL(location.href);u.searchParams.set("month",picker.value);location.href=u.toString()},{once:true})}
function render(rows,key,climate){const high=maxRow(rows,"high_c"),low=minRow(rows,"low_c"),gust=maxRow(rows,"peak_gust_kmh"),wettest=maxRow(rows,"rain_mm"),solar=maxRow(rows,"solar_peak_w_m2");const totalRain=rows.reduce((s,r)=>s+(usable(r.rain_mm)?Number(r.rain_mm):0),0);const wet=rows.filter(r=>usable(r.rain_mm)&&Number(r.rain_mm)>0).length;const dry=rows.filter(r=>usable(r.rain_mm)&&Number(r.rain_mm)<=0).length;const tempWeight=rows.reduce((sum,r)=>sum+(usable(r.temp_count)?Number(r.temp_count):0),0);const tempSum=rows.reduce((sum,r)=>sum+(usable(r.temp_sum_c)?Number(r.temp_sum_c):0),0);const weightedMean=tempWeight>0?tempSum/tempWeight:null;const meanTemp=usable(weightedMean)?Number(weightedMean):(key===currentMonthKey()&&usable(climate?.station_month_mean_temperature_c)?Number(climate.station_month_mean_temperature_c):null);const avgPressure=average(rows.map(r=>r.avg_pressure_hpa));const avgHigh=average(rows.map(r=>r.high_c));set("monthTitle",`${monthLabel(key)} · Parknacross`);set("monthSubtitle",rows.length?`${key===currentMonthKey()?"Month-to-date":"Archived monthly"} report based on ${rows.length} day${rows.length===1?"":"s"} of station data.`:"No archived days are available for this month.");set("monthStory",buildStory(rows,meanTemp,totalRain,high,low,gust,wettest));set("meanTemp",usable(meanTemp)?`${n(meanTemp)} °C`:"--");set("monthHigh",usable(high?.high_c)?`${n(high.high_c)} °C`:"--");set("monthHighDate",high?dateLabel(high.day):"--");set("monthLow",usable(low?.low_c)?`${n(low.low_c)} °C`:"--");set("monthLowDate",low?dateLabel(low.day):"--");set("monthRain",`${n(totalRain)} mm`);set("wettestDay",usable(wettest?.rain_mm)?`${n(wettest.rain_mm)} mm`:"--");set("wettestDayDate",wettest?dateLabel(wettest.day):"--");set("wetDays",String(wet));set("dryDays",String(dry));set("daysCaptured",String(rows.length));if(rows.length)set("capturePeriod",`${dateLabel(rows[0].day)} to ${dateLabel(rows[rows.length-1].day)}`);set("monthGust",usable(gust?.peak_gust_kmh)?`${n(gust.peak_gust_kmh)} km/h`:"--");set("monthGustDate",gust?dateLabel(gust.day):"--");set("monthPressure",usable(avgPressure)?`${n(avgPressure)} hPa`:"--");set("monthSolar",usable(solar?.solar_peak_w_m2)?`${Math.round(Number(solar.solar_peak_w_m2))} W/m²`:"--");set("monthSolarDate",solar?dateLabel(solar.day):"--");set("avgHigh",usable(avgHigh)?`${n(avgHigh)} °C`:"--");if(rows.length){const firstDay=Number(String(rows[0].day).slice(8,10));const current=key===currentMonthKey();set("partialNote",current?(firstDay>1?`Partial-month archive: data for this month begins on ${dateLabel(rows[0].day)}.`:"Month-to-date figures use all archived station days available so far."):(firstDay>1?`Partial archive for ${monthLabel(key)}: the first captured day is ${dateLabel(rows[0].day)}.`:`Archived report for ${monthLabel(key)}.`));}}
async function load(){try{const [daily,climate]=await Promise.all([getJSON("/daily?days=3660"),getJSON("/climate-summary").catch(()=>null)]);const all=Array.isArray(daily.days)?daily.days:[];const keys=new Set(all.map(r=>String(r.day||"").slice(0,7)).filter(k=>/^\d{4}-\d{2}$/.test(k)));let selected=new URL(location.href).searchParams.get("month");if(!keys.has(selected))selected=keys.has(currentMonthKey())?currentMonthKey():[...keys].sort().pop();populatePicker(keys,selected);render(all.filter(r=>String(r.day||"").startsWith(selected)),selected,climate);}catch(e){console.error("Monthly report:",e);set("monthSubtitle","The monthly report is temporarily unavailable.");set("monthStory","Archived station data could not be loaded. Please try again shortly.");}}
async function loadVerified(){try{const [daily,climate,stats]=await Promise.all([getJSON("/daily?days=3660"),getJSON("/climate-summary").catch(()=>null),getJSON("/stats").catch(()=>null)]);const all=Array.isArray(daily.days)?daily.days:[];const record=stats?.records?.peak_gust;if(usable(record?.epoch)&&usable(record?.value)){const day=new Date(Number(record.epoch)*1000).toLocaleDateString("en-CA",{timeZone:TZ});const row=all.find(item=>item.day===day);if(row)row.peak_gust_kmh=Number(record.value)+0.0001;}const keys=new Set(all.map(r=>String(r.day||"").slice(0,7)).filter(k=>/^\d{4}-\d{2}$/.test(k)));let selected=new URL(location.href).searchParams.get("month");if(!keys.has(selected))selected=keys.has(currentMonthKey())?currentMonthKey():[...keys].sort().pop();populatePicker(keys,selected);render(all.filter(r=>String(r.day||"").startsWith(selected)),selected,climate);}catch(e){console.error("Monthly report:",e);set("monthSubtitle","The monthly report is temporarily unavailable.");set("monthStory","Archived station data could not be loaded. Please try again shortly.");}}
document.addEventListener("DOMContentLoaded",()=>{set("year",new Date().getFullYear());loadVerified();});
