(() => {
 'use strict';const cfg=window.PARKNACROSS_CONFIG||{},base=window.PARKNACROSS_API_BASE||cfg.apiBase,usable=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
 const time=e=>new Date(e*1000).toLocaleString('en-IE',{timeZone:'Europe/Dublin',weekday:'short',hour:'2-digit',minute:'2-digit'});
 function choose(points,activity='walking',now=Date.now()/1000){const wind={walking:25,cycling:20,gardening:25}[activity]||25;const valid=(points||[]).filter(p=>Number.isFinite(p.epoch)&&p.epoch>=now&&p.epoch<=now+24*3600&&p.daylight===true&&usable(p.rain_mm)&&usable(p.wind_kmh)&&usable(p.temperature_c));const pairs=[];for(let i=0;i<valid.length-1;i++){const a=valid[i],b=valid[i+1];if(b.epoch-a.epoch!==3600||b.epoch+3600>now+24*3600)continue;const rain=Number(a.rain_mm)+Number(b.rain_mm),peakWind=Math.max(Number(a.wind_kmh),Number(b.wind_kmh));if(rain<=.2&&peakWind<=wind)pairs.push({from:a.epoch,to:b.epoch+3600,rain,wind:peakWind,temp:Math.min(Number(a.temperature_c),Number(b.temperature_c)),score:rain*100+peakWind});}return pairs.sort((a,b)=>a.score-b.score||a.from-b.from)[0]||null;}
 window.ParknacrossOutdoor={choose};
 document.addEventListener('DOMContentLoaded',()=>{const host=document.getElementById('outdoorOutlook');if(!host)return;const note=document.getElementById('outdoorStatus'),activity=document.getElementById('outdoorActivity');let feed=null;
 function render(){if(!feed||!Array.isArray(feed.points)||Date.now()-Date.parse(feed.fetched_at)>90*60000){note.textContent='The hourly outdoor outlook is unavailable. Check the official forecast below.';return;}const best=choose(feed.points,activity.value);note.textContent=best?`A lower-rain, lighter-wind daylight window: ${time(best.from)}–${time(best.to)}. Forecast rain ${best.rain.toFixed(1)} mm · wind up to ${best.wind.toFixed(0)} km/h · temperature from ${best.temp.toFixed(1)}°C.`:'No two-hour daylight period meets the selected rain and wind preferences in the next 24 hours. This is a planning aid; check the full forecast.';document.getElementById('outdoorSource').textContent=`Met Éireann point forecast · retrieved ${time(Date.parse(feed.fetched_at)/1000)} Irish time. Forecast conditions can change; this is not a safety assessment or a prediction of exactly what the station will measure.`;}
 async function load(){note.textContent='Checking the next 24 hours…';try{const response=await fetch(`${base}/outdoor-outlook`,{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Forecast unavailable');feed=await response.json();render();}catch{feed=null;render();}}
 activity.addEventListener('change',render);document.getElementById('refreshOutdoorOutlook').addEventListener('click',load);load();(window.ParknacrossRefresh?.every||setInterval)(load,30*60000);
 });
})();
