const API_BASE="https://parknacross-weather.dave-s-carter.workers.dev";const $=id=>document.getElementById(id);const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};const usable=v=>v!==null&&v!==undefined&&v!==""&&Number.isFinite(Number(v));const n=(v,d=1)=>usable(v)?Number(v).toFixed(d):"--";
async function getJSON(path){const r=await fetch(`${API_BASE}${path}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(d?.error)throw new Error(d.error);return d}
function dateFromRecord(record){if(!record)return null;if(record.received_at){const d=new Date(record.received_at);if(!Number.isNaN(d.getTime()))return d}if(usable(record.epoch)){const d=new Date(Number(record.epoch)*1000);if(!Number.isNaN(d.getTime()))return d}return null}
function fullDate(date){return date&&!Number.isNaN(date.getTime())?new Intl.DateTimeFormat("en-IE",{day:"numeric",month:"short",year:"numeric",timeZone:"Europe/Dublin"}).format(date):"--"}
function dayLabel(day){return day?fullDate(new Date(`${day}T12:00:00Z`)):"--"}
function maxRow(rows,field){return rows.reduce((b,r)=>!usable(r[field])?b:(!b||Number(r[field])>Number(b[field])?r:b),null)}
function isNextDay(a,b){if(!a||!b)return false;const da=new Date(`${a}T00:00:00Z`),db=new Date(`${b}T00:00:00Z`);return (db-da)===86400000}
function longestDrySpell(rows){let best=null,current=null;for(const r of rows){if(!usable(r.rain_mm))continue;const dry=Number(r.rain_mm)<=0;if(!dry){current=null;continue}if(current&&isNextDay(current.end,r.day)){current.end=r.day;current.days+=1}else current={start:r.day,end:r.day,days:1};if(!best||current.days>best.days)best={...current}}return best}
function showRecord(valueId,dateId,record,field,unit){set(valueId,record&&usable(record[field])?`${n(record[field])} ${unit}`:"--");set(dateId,record?fullDate(dateFromRecord(record)):"--")}
async function load(){try{const [stats,daily]=await Promise.all([getJSON("/stats"),getJSON("/daily?days=3660")]);const rows=Array.isArray(daily.days)?daily.days:[];showRecord("recordHigh","recordHighDate",stats.records?.high_temperature,"value","°C");showRecord("recordLow","recordLowDate",stats.records?.low_temperature,"value","°C");showRecord("recordGust","recordGustDate",stats.records?.peak_gust,"value","km/h");showRecord("recordHighPressure","recordHighPressureDate",stats.records?.high_pressure,"value","hPa");showRecord("recordLowPressure","recordLowPressureDate",stats.records?.low_pressure,"value","hPa");const wet=maxRow(rows,"rain_mm");set("recordWettest",wet?`${n(wet.rain_mm)} mm`:"--");set("recordWettestDate",wet?dayLabel(wet.day):"--");const solar=maxRow(rows,"solar_peak_w_m2");set("recordSolar",solar?`${Math.round(Number(solar.solar_peak_w_m2))} W/m²`:"--");set("recordSolarDate",solar?dayLabel(solar.day):"--");const ranges=rows.filter(r=>usable(r.high_c)&&usable(r.low_c)).map(r=>({...r,temp_range:Number(r.high_c)-Number(r.low_c)}));const range=maxRow(ranges,"temp_range");set("recordRange",range?`${n(range.temp_range)} °C`:"--");set("recordRangeDate",range?dayLabel(range.day):"--");const dry=longestDrySpell(rows);set("recordDrySpell",dry?`${dry.days} day${dry.days===1?"":"s"}`:"--");set("recordDrySpellDates",dry?(dry.start===dry.end?dayLabel(dry.start):`${dayLabel(dry.start)} – ${dayLabel(dry.end)}`):"--");const start=usable(stats.first_epoch)?new Date(Number(stats.first_epoch)*1000):null;set("archiveStart",start?fullDate(start):"--");set("archiveSamples",usable(stats.total_samples)?Number(stats.total_samples).toLocaleString("en-IE"):"--");set("archiveDays",rows.length.toLocaleString("en-IE"));set("recordsSubtitle",start?`All-time station records since ${fullDate(start)}. The record board updates automatically as the archive grows.`:"Live station records from the Parknacross archive.");}
catch(e){console.error("Records:",e);set("recordsSubtitle","Weather records are temporarily unavailable. Please try again shortly.");}}
document.addEventListener("DOMContentLoaded",()=>{set("year",new Date().getFullYear());load();setInterval(load,30*60*1000)});
