import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const source=n=>fs.readFileSync(new URL('../'+n,import.meta.url),'utf8');
// Hidden tabs perform no periodic reads; resuming triggers one request and protects in-flight work.
const events={},timers=[],document={hidden:true,addEventListener:(n,f)=>events[n]=f};const window={};vm.runInNewContext(source('visibility-refresh.js'),{window,document,Set,Promise,setInterval:f=>(timers.push(f),timers.length)});let calls=0,finish;window.ParknacrossRefresh.every(()=>{calls++;return new Promise(r=>finish=r)},1000);timers[0]();assert.equal(calls,0);document.hidden=false;events.visibilitychange();assert.equal(calls,1);timers[0]();events.visibilitychange();assert.equal(calls,1,'overlapping requests prevented');finish();await new Promise(r=>setImmediate(r));timers[0]();assert.equal(calls,2);finish();
// A bookmarked range overrides a remembered choice; selecting a rolling range clears fixed bounds.
const values=new Map([['parknacross:graph-hours','168']]),location={search:'?hours=48',href:'https://example.test/graphs.html?hours=48'},selectionWindow={addEventListener(){}};let url;
vm.runInNewContext(source('graph-selection.js'),{window:selectionWindow,document:{addEventListener(){}},location,localStorage:{getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)},history:{replaceState:(_,__,u)=>url=u},URL,URLSearchParams,Date,Number,Math,String,Event});assert.equal(selectionWindow.ParknacrossGraphSelection.get().hours,48);selectionWindow.ParknacrossGraphSelection.choose(720);assert.equal(values.get('parknacross:graph-hours'),'720');assert.equal(url.searchParams.get('hours'),'720');
const to=Math.floor(Date.now()/1000)-86400,from=to-3600,rangeWindow={addEventListener(){}};vm.runInNewContext(source('graph-selection.js'),{window:rangeWindow,document:{addEventListener(){}},location:{search:`?from=${from}&to=${to}`,href:`https://example.test/graphs.html?from=${from}&to=${to}`},history:{replaceState(){}},URL,URLSearchParams,Date,Number,Math,String,Event});assert.equal(rangeWindow.ParknacrossGraphSelection.historyPath(),`/history?from_epoch=${from}&to_epoch=${to}`);rangeWindow.ParknacrossGraphSelection.choose(24);assert.equal(rangeWindow.ParknacrossGraphSelection.get().range,null);
// Rain links use numeric event bounds and context, rather than a different day's current weather.
const rainWindow={PARKNACROSS_CONFIG:{apiBase:'https://example.test'}};vm.runInNewContext(source('rain.js').replace(/\}\)\(\);\s*$/,'window.testRainLink=eventGraphLink;})();'),{window:rainWindow,document:{addEventListener(){}},Date,Intl,Number,String,Math});const link=new URL(rainWindow.testRainLink({start_epoch:from,end_epoch:to}),'https://example.test');assert.equal(Number(link.searchParams.get('from')),from-1800);assert.equal(Number(link.searchParams.get('to')),to+1800);assert.equal(link.hash,'#gRain');assert.equal(rainWindow.testRainLink({start_epoch:'bad'}),'history.html');
console.log('PASS: hidden-tab refresh suppression, immediate non-overlapping resume, remembered/bookmarked ranges and date-correct rain-event links.');

// Switching archive dates while a photograph request is pending cannot show the old date's image.
const historySource=source('history.js'),photoSource=historySource.slice(historySource.indexOf('let photoRequest=0;'),historySource.indexOf('async function loadDay(day)'));
const photoNodes=new Map(),photoEl=id=>{if(!photoNodes.has(id))photoNodes.set(id,{hidden:true,textContent:'',removeAttribute(n){delete this[n]}});return photoNodes.get(id)},resolvers=new Map();
const photoContext={selectedArchiveDay:'2026-10-01',API_BASE:'https://example.test',$:photoEl,set:(id,text)=>photoEl(id).textContent=text,getJSON:url=>new Promise(r=>resolvers.set(new URL(url).searchParams.get('day'),r)),encodeURIComponent,setTimeout,clearTimeout};vm.createContext(photoContext);vm.runInContext(photoSource,photoContext);const old=photoContext.loadHistoricalSky('2026-10-01');photoContext.selectedArchiveDay='2026-10-02';const next=photoContext.loadHistoricalSky('2026-10-02');resolvers.get('2026-10-01')({day:'2026-10-01',photo:{photo_id:'old',caption:'Old'}});await old;assert.equal(photoEl('historicalSkyImage').src,undefined);resolvers.get('2026-10-02')({day:'2026-10-02',photo:{photo_id:'new',caption:'New'}});await next;assert.match(photoEl('historicalSkyImage').src,/day=2026-10-02.*photo_id=new/);photoEl('historicalSkyImage').onload();assert.equal(photoEl('historicalSkyImage').hidden,false);assert.equal(photoEl('historicalSkyCaption').textContent,'New');console.log('PASS: delayed historical photographs cannot overwrite the newly selected day.');
