import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import {DatabaseSync} from 'node:sqlite';
import {createECDH,hkdfSync,createDecipheriv,createPublicKey,verify} from 'node:crypto';
const source=await fs.readFile(new URL('../_worker/worker.mjs',import.meta.url),'utf8');
const backend=await import('data:text/javascript;base64,'+Buffer.from(source+'\nexport {orderedStationDayResolver,stationDaySqlExpression,stationDayEpochRange,buildArchiveCoverage,buildRainEvents,pushEncrypt,pushVapid,pushPreferences,pushEndpointAllowed,sendWeatherPush,backgroundWeatherEvents,solarAltitude};').toString('base64'));
const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE parknacross_meta_v1(key TEXT PRIMARY KEY,value TEXT);CREATE TABLE weather_readings_v2(epoch INTEGER PRIMARY KEY,received_at TEXT,rain_rate_mm_h REAL,rain_daily_mm REAL)");
const env={DB:{prepare(sql){let values=[];return {bind(...v){values=v;return this;},async first(){return db.prepare(sql).get(...values)||null;},async all(){return {results:db.prepare(sql).all(...values)};},async run(){const r=db.prepare(sql).run(...values);return {success:true,meta:{changes:Number(r.changes)}};}};}}};
// Real SQL archive test, including the 23/25-hour Irish clock-change days.
const day=backend.orderedStationDayResolver();for(const [key,hours] of [['2026-03-29',23],['2026-10-25',25]]){const range=backend.stationDayEpochRange(key);assert.equal((range.endEpoch-range.startEpoch)/3600,hours);assert.equal(day(range.startEpoch),key);assert.equal(day(range.endEpoch-1),key);assert.notEqual(day(range.endEpoch),key);}
for(const key of ['2026-03-29','2026-10-25']){const bounds=backend.stationDayEpochRange(key);db.prepare('INSERT INTO weather_readings_v2 VALUES (?,?,0,0)').run(bounds.startEpoch,new Date(bounds.startEpoch*1000).toISOString());db.prepare('INSERT INTO weather_readings_v2 VALUES (?,?,0,0)').run(bounds.endEpoch-300,new Date((bounds.endEpoch-300)*1000).toISOString());const query=`SELECT ${backend.stationDaySqlExpression(key,key)} AS day, COUNT(*) AS n FROM weather_readings_v2 WHERE epoch>=? AND epoch<? GROUP BY day`;assert.deepEqual({...db.prepare(query).get(bounds.startEpoch,bounds.endEpoch)},{day:key,n:2});}db.exec('DELETE FROM weather_readings_v2');
const now=Math.floor(Date.now()/1000),today=new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Dublin'}),range=backend.stationDayEpochRange(today);const insert=db.prepare('INSERT INTO weather_readings_v2 VALUES (?,?,?,?)');for(let epoch=range.startEpoch;epoch<=now;epoch+=300)insert.run(epoch,new Date(epoch*1000).toISOString(),epoch===range.startEpoch+600?3:0,epoch>=range.startEpoch+600?.2:0);
const coverage=await backend.buildArchiveCoverage(env,371);assert.equal(coverage.days.length,1);assert.equal(coverage.days[0].coverage_percent,100);assert.equal(coverage.days[0].day,today);const events=await backend.buildRainEvents(env,new URL('https://test/rain-events?days=30'));assert.equal(events.event_count,1);assert.equal(events.events[0].total_mm,.2);
// Encryption is decrypted by independent Node primitives, not the implementation's helpers.
const ua=createECDH('prime256v1');ua.generateKeys();const auth=Buffer.alloc(16,9),sub={endpoint:'https://fcm.googleapis.com/fcm/send/test-only',p256dh:ua.getPublicKey().toString('base64url'),auth:auth.toString('base64url')},message={title:'Test weather',body:'Test-only payload'};
const encrypted=Buffer.from(await backend.pushEncrypt(sub,message)),salt=encrypted.subarray(0,16),publicKey=encrypted.subarray(21,86),cipher=encrypted.subarray(86),shared=ua.computeSecret(publicKey),ikm=hkdfSync('sha256',shared,auth,Buffer.concat([Buffer.from('WebPush: info\0'),ua.getPublicKey(),publicKey]),32),cek=hkdfSync('sha256',ikm,salt,Buffer.from('Content-Encoding: aes128gcm\0'),16),nonce=hkdfSync('sha256',ikm,salt,Buffer.from('Content-Encoding: nonce\0'),12),decipher=createDecipheriv('aes-128-gcm',cek,nonce);decipher.setAuthTag(cipher.subarray(-16));const plain=Buffer.concat([decipher.update(cipher.subarray(0,-16)),decipher.final()]);assert.equal(plain.at(-1),2);assert.deepEqual(JSON.parse(plain.subarray(0,-1).toString()),message);
const vapid=await backend.pushVapid(env);assert.equal((await backend.pushVapid(env)).publicKey,vapid.publicKey);const fetchBefore=globalThis.fetch;let sent;globalThis.fetch=async(url,options)=>{sent={url,options};return new Response('',{status:201});};await backend.sendWeatherPush(sub,message,vapid);globalThis.fetch=fetchBefore;const jwt=sent.options.headers.Authorization.match(/t=([^,]+)/)[1],parts=jwt.split('.'),claims=JSON.parse(Buffer.from(parts[1],'base64url'));assert.equal(claims.aud,'https://fcm.googleapis.com');assert.ok(verify('sha256',Buffer.from(parts[0]+'.'+parts[1]),{key:createPublicKey({key:vapid.privateJwk,format:'jwk'}),dsaEncoding:'ieee-p1363'},Buffer.from(parts[2],'base64url')));assert.equal(sent.options.redirect,'error');
assert.equal(backend.pushEndpointAllowed('https://localhost/push'),false);assert.equal(backend.pushEndpointAllowed('https://fcm.googleapis.com.evil.test/push'),false);assert.equal(backend.pushEndpointAllowed('https://fcm.googleapis.com/push'),true);
// Subscription ownership, status and unsubscribe use actual SQLite, including rejection of unowned changes.
const userKeys={p256dh:sub.p256dh,auth:sub.auth},req=(body,token)=>new Request('https://worker.test/push/subscription',{method:'POST',headers:{Origin:'https://parknacrossweather.ie','Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body)});const prefs=backend.pushPreferences({rainStart:true,gust:true,gustKmh:35});let response=await backend.default.fetch(req({action:'save',subscription:{endpoint:sub.endpoint,keys:userKeys},preferences:prefs}),env,{});assert.equal(response.status,200);const saved=await response.json();assert.ok(saved.management_token);response=await backend.default.fetch(req({action:'status',subscription:{endpoint:sub.endpoint}},'wrong-token'),env,{});assert.equal(response.status,401);response=await backend.default.fetch(req({action:'status',subscription:{endpoint:sub.endpoint}},saved.management_token),env,{});assert.equal(response.status,200);assert.equal((await response.json()).preferences.gustKmh,35);response=await backend.default.fetch(req({action:'remove',subscription:{endpoint:sub.endpoint}},saved.management_token),env,{});assert.equal(response.status,200);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM weather_push_subscriptions_v1').get().n,0);
// Freshness, thresholds, cooldowns and quiet hours are evaluated without sending notifications.
const current={epoch:now,rain_daily_mm:0,rain_rate_mm_h:0,wind_gust_kmh:40,temperature_c:10},previous={epoch:now-60,wind_gust_kmh:20,temperature_c:10,rain_rate_mm_h:0,rain_daily_mm:0};assert.equal(backend.backgroundWeatherEvents(current,previous,prefs,now).events[0].kind,'gust');assert.equal(backend.backgroundWeatherEvents({...current,epoch:now-1000},previous,prefs,now).events.length,0);assert.equal(backend.backgroundWeatherEvents(current,{...previous,cooldowns:{gust:now-60}},prefs,now).events.length,0);assert.equal(backend.backgroundWeatherEvents(current,previous,{...prefs,quietEnabled:true,quietStart:0,quietEnd:0},now).events.length,0);assert.equal(backend.backgroundWeatherEvents(current,{},prefs,now).events.length,0);
assert.ok(backend.solarAltitude(Date.parse('2026-06-21T12:00:00Z')/1000,52.6247,-6.25)>50);assert.ok(backend.solarAltitude(Date.parse('2026-06-21T00:00:00Z')/1000,52.6247,-6.25)<0);
// Actual Rain/Radar load functions may not relabel yesterday's sample as today.
const nodes=new Map(),document={getElementById(id){if(!nodes.has(id))nodes.set(id,{textContent:'',innerHTML:''});return nodes.get(id);},addEventListener(){}},old={received_at:'2026-01-01T12:00:00Z',rain_daily_mm:7,rain_rate_mm_h:3},context={window:{PARKNACROSS_CONFIG:{apiBase:'https://fixture'}},document,Date,Intl,console,setTimeout,fetch:async url=>({ok:true,json:async()=>url.endsWith('/current')?old:url.endsWith('/rain-summary')?{today_mm:0}:url.includes('/history')?{readings:[]}:{}})};vm.createContext(context);vm.runInContext((await fs.readFile(new URL('../rain.js',import.meta.url),'utf8')).replace('})();','window.auditLoad=load;})();'),context);await context.window.auditLoad();assert.equal(nodes.get('rainToday').textContent,'0.0 mm');assert.equal(nodes.get('rainNow').textContent,'--');vm.runInContext((await fs.readFile(new URL('../radar.js',import.meta.url),'utf8')).replace('})();','window.auditLoad=loadRain;})();'),context);await context.window.auditLoad();assert.equal(nodes.get('radarRainToday').textContent,'--');assert.equal(nodes.get('radarRainRate').textContent,'--');
const visitor={window:{addEventListener(){}},document:{addEventListener(){}},Date,Intl,Number};vm.createContext(visitor);vm.runInContext(await fs.readFile(new URL('../visitor-insights.js',import.meta.url),'utf8'),visitor);assert.equal(visitor.window.ParknacrossRainEvidence.evidence(old,[],now).fresh,false);
const outdoor={window:{},document:{addEventListener(){}},Date,Intl,Number};vm.createContext(outdoor);vm.runInContext(await fs.readFile(new URL('../outdoor-outlook.js',import.meta.url),'utf8'),outdoor);const points=[0,1].map(h=>({epoch:now+h*3600,daylight:true,rain_mm:0,wind_kmh:10,temperature_c:12}));assert.ok(outdoor.window.ParknacrossOutdoor.choose(points,'walking',now));assert.equal(outdoor.window.ParknacrossOutdoor.choose(points.map(p=>({...p,rain_mm:null})),'walking',now),null);assert.equal(outdoor.window.ParknacrossOutdoor.choose(points.map(p=>({...p,daylight:false})),'walking',now),null);
console.log('PASS: archive/DST, real SQL subscriptions/ownership, independent push decryption/VAPID signatures, thresholds/quiet hours/stale samples, rain midnight and honest outdoor guidance.');
