import fs from 'node:fs';import vm from 'node:vm';import a from 'node:assert/strict';
const src=name=>fs.readFileSync(new URL('../'+name,import.meta.url),'utf8');
function element(){return {hidden:false,value:'',textContent:'',dataset:{},children:[],events:{},classList:{add(){}},append(...x){this.children.push(...x)},replaceChildren(...x){this.children=x},addEventListener(n,f){this.events[n]=f},removeAttribute(n){delete this[n]},setAttribute(n,v){this[n]=v}};}
const els=new Map(),el=id=>{if(!els.has(id))els.set(id,element());return els.get(id)};
const document={getElementById:el,createElement:element,addEventListener(){},querySelectorAll:()=>[]};
const values=new Map([['parknacrossAdminKey','test-only']]);const storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};
const events={},requests=[];const window={PARKNACROSS_CONFIG:{apiBase:'https://example.test'},addEventListener:(n,f)=>events[n]=f,dispatchEvent:event=>events[event.type]?.()};
vm.runInNewContext(src('admin-tools.js'),{document,window,sessionStorage:storage,URL,AbortSignal,Event,Promise,Date,Blob,fetch:async(url,options)=>{requests.push({url,options});return {ok:true,status:200,blob:async()=>new Blob(['test'],{type:'image/png'}),json:async()=>url.endsWith('/weather-window/sky')?{override:{sky:'clear'}}:url.includes('/archive/admin')?{day:new URL(url).searchParams.get('day'),items:[{photo_id:'one',day:'2026-10-07'},{photo_id:'two',day:'2026-10-06'}],total:2}:{items:[{day:'2026-10-07',network:'x',text:'Saved copy',status:'sent',public_url:'javascript:alert(1)'}],note:'Recording enabled'}};}});
await new Promise(r=>setImmediate(r));a.equal(el('adminWorkspace').hidden,false);a.equal(el('adminSky').value,'clear','override envelope is read correctly');a.ok(requests.every(x=>x.options.headers['X-Parknacross-Admin-Key']==='test-only'));a.equal(el('postHistory').children.length,1);a.equal(el('postHistory').children[0].children.filter(x=>x.href).length,0,'unsafe links rejected');
a.match(el('archiveCaption').textContent,/photo 1 of 2/);a.equal(el('archivePrevious').disabled,true);el('archiveNext').events.click();await new Promise(r=>setImmediate(r));a.match(el('archiveCaption').textContent,/photo 2 of 2/);a.equal(el('archiveNext').disabled,true);a.ok(requests.some(x=>x.url.endsWith('photo_id=two')));el('archiveDay').value='2026-10-06';el('archiveDay').events.change();await new Promise(r=>setImmediate(r));a.ok(requests.some(x=>x.url.includes('day=2026-10-06')));
el('adminSignOut').events.click();a.equal(storage.getItem('parknacrossAdminKey'),null);a.equal(el('adminWorkspace').hidden,true);a.equal(el('adminLogin').hidden,false);a.equal(el('postHistory').children.length,0);
const freshWindow={};vm.runInNewContext(src('source-freshness.js'),{window:freshWindow,document,Date,Number});const ago=new Date(Date.now()-48*3600000).toISOString();freshWindow.ParknacrossFreshness.render('fresh',{freshness:{cached:true,retrieved_at:ago}},ago,24,'Observed');a.equal(el('fresh').dataset.state,'old');a.match(el('fresh').textContent,/cached response/);a.match(el('fresh').textContent,/older than expected/);
const chartWindow={PARKNACROSS_CONFIG:{}},graphs=src('graphs.js').replace(/\}\)\(\);\s*$/,'window.testGraphs={make,load,getCharts:()=>charts,applyExactTimeBounds};})();');
class Chart{static defaults={font:{}};constructor(node,config){this.node=node;Object.assign(this,config)}update(){}resize(){}}
vm.runInNewContext(graphs,{window:chartWindow,document,Chart,Date,Intl,Number,Set,Map,Math,setInterval(){}});chartWindow.testGraphs.make();const charts=chartWindow.testGraphs.getCharts();a.equal(charts.sd.data.datasets.length,1);a.equal(charts.ec.data.datasets.length,1);a.equal(charts.sd.data.datasets[0].label,'Soil temperature');a.equal(charts.ec.data.datasets[0].label,'Conductivity');a.equal(charts.sd.options.scales.y.afterFit,charts.ec.options.scales.y.afterFit);chartWindow.testGraphs.applyExactTimeBounds([{epoch:1791363493}]);a.equal(charts.sd.options.scales.x.min,charts.ec.options.scales.x.min);a.equal(charts.sd.options.scales.x.max,charts.ec.options.scales.x.max);
console.log('PASS: calendar photo browsing, previous/next boundaries, private admin sign-in/out, sky override readback, safe history links, cached/old source labels and separated soil charts with matching time bounds.');
