import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {runInNewContext} from 'node:vm';
const window={};
runInNewContext(await readFile(new URL('../weather-window-sky.js',import.meta.url),'utf8'),{window});
const sky=window.ParknacrossWeatherSky;
for(const [text,expected] of [['Clear and sunny','clear'],['Few clouds','mostly-clear'],['Cloudy with sunny spells','partly-cloudy'],['Overcast and persistent rain','overcast'],['Mostly dry','unknown']]) assert.equal(sky.classify(text),expected);
const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Dublin',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const forecast={day,fetchedAt:Date.now(),today:'Sunny this morning, but cloudier this afternoon. Overcast this evening.',tonight:'Clear skies tonight.'};
for(const [hour,expected] of [[9,'clear'],[14,'cloudy'],[18,'overcast']]) assert.equal(sky.resolve(forecast,{hour,isNight:false,day}).sky,expected);
assert.equal(sky.resolve(forecast,{hour:21,isNight:true,day}).sky,'clear');
assert.equal(sky.resolve({...forecast,fetchedAt:Date.now()-3*3600000},{hour:9,isNight:false,day}).sky,'unknown');
const elements=new Map(),listeners=new Map();
function el(id){if(!elements.has(id))elements.set(id,{textContent:'',dataset:{},style:{setProperty(k,v){this[k]=v}},setAttribute(k,v){this[k]=v},querySelector(){return {style:{}}},addEventListener(){},hidden:true});return elements.get(id);}
const doc={getElementById:el,addEventListener(){}};
window.addEventListener=(n,f)=>listeners.set(n,f);
const source=await readFile(new URL('../weather-window.js',import.meta.url),'utf8');
runInNewContext(source,{document:doc,window,console,Math,Date,Number,String,Intl,URLSearchParams,location:{search:''},setInterval(){},fetch:async()=>({ok:false})});
listeners.get('parknacross:weather-window-forecast')({detail:{...forecast,today:'Clear and sunny.'}});
const detail={isNight:false,isDaylight:true,rainDetected:false,current:{epoch:Date.now()/1000,wind_speed_kmh:3,wind_gust_kmh:5,wind_direction_deg:90,rain_rate_mm_h:0,solar_w_m2:45}};
listeners.get('parknacross:weather-window-observation')({detail});
assert.equal(el('weatherWindowScene').dataset.sky,'clear');
assert.equal(el('weatherWindowScene').dataset.light,'day','weak morning sunlight does not imply a grey sky');
listeners.get('parknacross:weather-window-forecast')({detail:{...forecast,today:'Overcast with persistent rain.'}});
assert.equal(el('weatherWindowScene').dataset.sky,'overcast');
assert.equal(el('weatherWindowScene').dataset.rain,'none','forecast rain is not animated as observed rainfall');
listeners.get('parknacross:weather-window-observation')({detail:{...detail,isNight:true,current:{...detail.current,rain_rate_mm_h:2}}});
assert.equal(el('weatherWindowScene').dataset.light,'night');
assert.equal(el('weatherWindowScene').dataset.rain,'measured');
assert.equal(el('weatherWindowSkyAdmin').hidden,true);
console.log('Weather Window forecast periods, stale fallback, blue morning sky, observation-only rain and normal-visitor admin controls pass.');
