import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const now=Math.floor(Date.now()/1000),day=new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Dublin'});
const current={epoch:now,received_at:new Date(now*1000).toISOString(),temperature_c:12,humidity:70,wind_speed_kmh:8,wind_gust_kmh:13,wind_direction_deg:90,pressure_hpa:1017,rain_daily_mm:0,rain_rate_mm_h:0,solar_w_m2:100,uv_index:1};
const rows=Array.from({length:13},(_,i)=>({...current,epoch:now-(12-i)*300,received_at:new Date((now-(12-i)*300)*1000).toISOString()}));
const csv='epoch,observation_time_ireland,soil_moisture_pct,lightning_strikes,lightning_last_strike_time_ireland\r\n'+now+',test,39,,\r\n';
test.beforeEach(async({page})=>{await page.route('**/static.cloudflareinsights.com/**',r=>r.fulfill({body:'',contentType:'application/javascript'}));await page.route('**/*.workers.dev/**',async r=>{const p=new URL(r.request().url()).pathname;let d={};if(p==='/current')d=current;if(p==='/history')d={readings:rows};if(p==='/rain-summary')d={today_mm:0};if(p==='/daily')d={days:[{day,high_c:12,low_c:10,rain_mm:0}]};if(p==='/stats')d={first_epoch:now-86400,total_samples:100,records:{high_temperature:{value:12,epoch:now-3600}}};if(p==='/met/forecast')d={today:'Dry.',tonight:'Dry.',tomorrow:'Dry.'};if(p==='/met/warnings')d={warnings:[]};if(p==='/sky-photo/meta')d={available:false};if(p==='/outdoor-outlook')d={fetched_at:new Date().toISOString(),points:[1,2].map(h=>({epoch:now+h*3600,daylight:true,temperature_c:12,wind_kmh:10,rain_mm:0}))};if(p==='/export.csv')return r.fulfill({contentType:'text/csv',body:csv});if(p==='/push/public-key')return r.fulfill({status:503,contentType:'application/json',body:'{}'});await r.fulfill({contentType:'application/json',body:JSON.stringify(d)});});});
test('saved graph views retain metric and exact zoom after reload',async({page})=>{await page.goto('/graphs.html');await expect(page.locator('#graphCount')).not.toHaveText('Loading…');await page.evaluate(()=>{const c=Chart.getChart(document.getElementById('gTemp'));ParknacrossChartExplorer.zoom(c.scales.x.min+300000,c.scales.x.max-300000);});await page.getByText('Save a favourite graph view',{exact:true}).click();await page.locator('#savedGraphName').fill('Rain window');await page.locator('#savedGraphMetric').selectOption('gRain');await page.locator('#saveGraphView').click();await expect(page.locator('#savedGraphStatus')).toContainText('View saved');await page.reload();await page.getByText('Save a favourite graph view',{exact:true}).click();await page.locator('#savedGraphPicker').selectOption('0');await page.locator('#openSavedGraph').click();await expect(page).toHaveURL(/from=\d+&to=\d+&metric=gRain#gRain/);await expect(page.locator('#graphRangeTitle')).toHaveText('Selected event window');});
test('records link to the exact observation window',async({page})=>{await page.goto('/records.html');await expect(page.locator('#recordHigh')).toHaveText('12.0 °C');const link=page.locator('#recordHigh').locator('..').locator('a');await expect(link).toHaveAttribute('href',new RegExp('graphs.html\\?from='+(now-7200)+'&to='+now+'#gTemp'));});
test('summary CSV uses complete canonical sensor fields',async({page})=>{await page.goto('/summary.html');await expect(page.locator('#downloadCsvButton')).toBeEnabled();const downloadPromise=page.waitForEvent('download');await page.locator('#downloadCsvButton').click();const download=await downloadPromise,text=await readFile(await download.path(),'utf8');expect(text.replace(/^\uFEFF/,'')).toBe(csv);await expect(page.locator('#actionStatus')).toContainText('Complete CSV downloaded');});
test('outdoor outlook describes forecast conditions and has a failure fallback',async({page})=>{await page.goto('/index.html');await expect(page.locator('#outdoorStatus')).toContainText('lower-rain, lighter-wind daylight window');await expect(page.locator('#outdoorSource')).toContainText('Met Éireann point forecast');await page.route('**/outdoor-outlook',r=>r.fulfill({status:503,body:'{}'}));await page.locator('#refreshOutdoorOutlook').click();await expect(page.locator('#outdoorStatus')).toContainText('unavailable');});
test('unavailable background service retains existing local alert controls',async({page})=>{await page.goto('/station.html');await page.getByText('Background alerts, thresholds & quiet hours',{exact:true}).click();await expect(page.locator('#backgroundAlertStatus')).toContainText(/temporarily unavailable|not supported/);await expect(page.locator('#backgroundAlertToggle')).toBeDisabled();await expect(page.locator('#alertsEnableButton')).toBeEnabled();await page.locator('#alertGustThreshold').fill('35');await page.locator('#alertGustThreshold').press('Tab');expect(await page.evaluate(()=>PWAlerts.loadSettings().gustKmh)).toBe(35);await page.reload();await page.getByText('Background alerts, thresholds & quiet hours',{exact:true}).click();await expect(page.locator('#alertGustThreshold')).toHaveValue('35');});

test('status surfaces failed rain-event and coverage feeds',async({page})=>{await page.route('**/health',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({status:'ok',database:'connected',archive_ingest:{latest_age_seconds:30}})}));await page.route('**/rain-events?**',r=>r.fulfill({status:503,body:'{"error":"Unavailable"}'}));await page.route('**/coverage?**',r=>r.fulfill({status:503,body:'{"error":"Unavailable"}'}));await page.goto('/status.html');await expect(page.locator('#rainEventsFeedBadge')).toHaveText('Unavailable');await expect(page.locator('#coverageFeedBadge')).toHaveText('Unavailable');await expect(page.locator('#overallText')).toContainText('warning');});
